"use client";

import { useEffect, useState } from "react";
import { Bot, BrainCircuit, Check, KeyRound, LoaderCircle, Settings2, Sparkles } from "lucide-react";

interface Settings { automation: { transcribe: boolean; analyzeRequested: boolean; analyzeEffective: boolean }; integrations: { glm: boolean; groq: boolean; discord: boolean }; agents: Array<{ id: string; name: string; model: string; responsibility: string }> }

export function SettingsWorkspace() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { void fetch("/api/settings").then((response) => response.json()).then((value: Settings) => setSettings(value)); }, []);
  async function update(change: { transcribe?: boolean; analyze?: boolean }) { setSaving(true); const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(change) }); setSettings(await response.json() as Settings); setSaving(false); setNotice("Configuração salva no .env. Reinicie o bot se ele estiver ligado."); }
  return <div className="page settings-page"><header className="page-header"><div><span className="eyebrow">Preferências locais</span><h1>Configurações</h1><p>Controle automações e confira integrações sem expor nenhuma chave secreta.</p></div>{saving && <span className="saving-label"><LoaderCircle size={14} className="spin-icon" /> Salvando</span>}</header>{notice && <div className="success-banner settings-notice">{notice}</div>}<div className="settings-grid"><section className="panel settings-section"><div className="settings-heading"><span><Bot size={20} /></span><div><h2>Fluxo automático de calls</h2><p>Executado pelo processo do Discord bot depois que uma gravação termina.</p></div></div>{settings ? <div className="setting-rows"><SettingToggle label="Transcrever após gravar" description="Envia cada trilha à Groq e monta a conversa cronológica." checked={settings.automation.transcribe} onChange={(checked) => void update({ transcribe: checked })} /><SettingToggle label="Analisar após transcrever" description="Gera o relatório do analista de call. Depende da opção acima." checked={settings.automation.analyzeRequested} effective={settings.automation.analyzeEffective} onChange={(checked) => void update({ analyze: checked })} /></div> : <div className="skeleton settings-skeleton" />}</section><section className="panel settings-section"><div className="settings-heading"><span><KeyRound size={20} /></span><div><h2>Integrações</h2><p>A interface informa apenas se cada chave está configurada.</p></div></div>{settings && <div className="integration-list"><Integration name="GLM / z.ai" detail="Chat, analista e curador" configured={settings.integrations.glm} /><Integration name="Groq" detail="Transcrição de áudio" configured={settings.integrations.groq} /><Integration name="Discord" detail="Conexão do bot Clara" configured={settings.integrations.discord} /></div>}</section><section className="panel settings-section agents-settings"><div className="settings-heading"><span><BrainCircuit size={20} /></span><div><h2>Agentes</h2><p>Os modelos são definidos por perfil, não por uma variável global.</p></div></div><div className="agent-settings-list">{settings?.agents.map((agent) => <div key={agent.id}><span><Sparkles size={15} /></span><div><strong>{agent.name}</strong><small>{agent.responsibility}</small></div><code>{agent.model}</code></div>)}</div></section><section className="panel security-card"><Settings2 size={22} /><div><strong>Privacidade por desenho</strong><p>O servidor web fica em <code>127.0.0.1</code>. Memórias, transcrições e chaves não são enviadas ao navegador além do conteúdo que você abre.</p></div></section></div></div>;
}

function SettingToggle({ label, description, checked, effective = checked, onChange }: { label: string; description: string; checked: boolean; effective?: boolean; onChange: (checked: boolean) => void }) { return <label className="setting-row"><div><strong>{label}</strong><small>{description}</small>{checked && !effective && <em>Inativa enquanto a transcrição automática estiver desligada.</em>}</div><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="switch" /></label>; }
function Integration({ name, detail, configured }: { name: string; detail: string; configured: boolean }) { return <div className="integration"><span className={configured ? "configured" : ""}>{configured ? <Check size={14} /> : "!"}</span><div><strong>{name}</strong><small>{detail}</small></div><b>{configured ? "configurada" : "ausente"}</b></div>; }
